apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nfs-client-provisioner
  namespace: kube-system
  annotations:
    fluxcd.io/automated: "true"
    fluxcd.io/tag.chart-image: semver:~v3.1
spec:
  releaseName: nfs-client-provisioner
  rollback:
    enable: true
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-client-provisioner
    version: 1.2.6
  values:
    image:
      repository: quay.io/external_storage/nfs-client-provisioner
      tag: v3.1.0-k8s1.11
    nfs:
      server: "nsf-server"
      path: "/exports/k8s-nfs"
    storageClass:
      defaultClass: true