apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nfs-server-provisioner
  namespace: nfs-server
spec:
  releaseName: nfs-server-provisioner
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: nfs-server-provisioner
    namespace: nfs-server
    version: 0.3.1
  values:
    image:
      repository: quay.io/kubernetes_incubator/nfs-provisioner
      tag: v2.2.1-k8s1.12
    persistence:
      enabled: true
      storageClass: "-"
      size: 600Gi
    storageClass:
      defaultClass: true
    nodeSelector:
      nvme: "true"