apiVersion: v1
kind: PersistentVolume
metadata:
  namespace: nfs-server
  name: data-nfs-server-provisioner-0
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 600Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/exports"
  claimRef:
    namespace: nfs-server
    name: data-nfs-server-provisioner-0