---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: rook-ceph
  namespace: rook-ceph
  annotations:
    fluxcd.io/automated: "false"
spec:
  releaseName: rook-ceph
  chart:
    repository: https://charts.rook.io/release
    name: rook-ceph
    version: v1.1.2
  values:
    image:
      prefix: rook
      repository: rook/ceph
      tag: sha256:7604e4d6e50b0a50ee6288b18980208fb62acabe8fcc1724ff3e72c69035f16a
      pullPolicy: IfNotPresent
    csi:
      kubeletDirPath: /var/lib/rancher/k3s/agent/kubelet