apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.8.3
  values:
    configInline:
      address-pools:
      - name: default
        protocol: layer2
        addresses:
        - 172.4.21.2
    prometheus:
      scrapeAnnotations: true