apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: metallb
  namespace: metallb-system
  annotations:
    flux.weave.works/automated: "false"
spec:
  releaseName: metallb
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: metallb
    version: 0.8.3
  values:
    configInline:
      address-pools:
      - name: bgp
        protocol: bgp
        addresses:
        - 172.4.21.2-172.4.21.100
      peers:
      - peer-address: 192.168.0.1
        peer-asn: 64512
        my-asn: 64512
    prometheus:
      scrapeAnnotations: true

