---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: nginx-ingress
  namespace: ingress
spec:
  releaseName: nginx-ingress
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com
    name: nginx-ingress
    version: 1.24.3
  # values:
  #   controller:
  #     service:
  #       annotations:
  #         external-dns.alpha.kubernetes.io/hostname: "*.cole.boxboat.io"
  #         external-dns: "wildcard"