---
apiVersion: flux.weave.works/v1beta1
kind: HelmRelease
metadata:
  name: traefik
  namespace: ingress
  annotations:
    flux.weave.works/automated: "true"
    flux.weave.works/tag.chart-image: semver:~1
spec:
  releaseName: traefik
  chart:
    repository: https://kubernetes-charts.storage.googleapis.com/
    name: traefik
    version: 1.78.2
  values:
    rbac:
      enabled: true
    loadBalancerIP: 172.4.21.2
    dashboard:
      enabled: true
      domain: traefik.colestestserver.com
    externalTrafficPolicy: Local
    replicas: 3
    resources:
      requests:
        memory: "64Mi"
        cpu: "250m"
      limits:
        memory: "128Mi"
        cpu: "500m"
