apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: ddns
  namespace: ddns
spec:
  schedule: "*/1 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - image: crazymax/ddns-route53:1.6.0
            name: ddns-route53
            command: [/usr/local/bin/ddns-route53]
            args: [ "--config", "/conf/ddns-route53.yaml" ]
            volumeMounts:
            - name: config
              mountPath: /conf/
            resources: {}
          volumes:
          - name: config
            secret:
              secretName: ddns
          restartPolicy: OnFailure